-- Triangle, pentagonal, and hexagonal numbers are generated by the following
-- formulae:
-- Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
-- Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
-- Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.
-- Find the next triangle number that is also pentagonal and hexagonal.

n * (n + 1) / 2 == n * (3 * n -1) /2 == n * (2 * n -1)

tris = [tri | n <- [285..], let tri = n * (n + 1) / 2] 
pens = [pen | n <- [165..], let pen = n * (3 * n -1 ) / 2] 
hexs = [hex | n <- [143..], let hex = n * (2 * n -1 )]

ans = [x | x <- tris, y <- pens, z <- hexs, x == y && x == z]

main = print $ head $ filter (== 40755) $ ans